# Generated by Django 3.2.16 on 2023-03-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0016_auto_20230321_1216'),
        ('sensordata', '0005_sensordata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='sensordata',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensortype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.sensortype'),
        ),
    ]
