# Generated by Django 3.2.16 on 2023-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0006_auto_20230321_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
