# Generated by Django 3.2.19 on 2023-08-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0007_auto_20230525_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensoroffset',
            old_name='sensor_A',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='sensoroffset',
            old_name='sensor_B',
            new_name='imu',
        ),
    ]
