# Generated by Django 3.1.14 on 2023-10-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20220211_2218'),
        ('sensordata', '0009_auto_20231005_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoroffset',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
