# Generated by Django 3.2.19 on 2023-09-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_alter_fileupload_file'),
        ('sensordata', '0011_auto_20230917_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='file_upload_project2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectannotation_file', to='data_import.fileupload'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='file_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataimport_file', to='data_import.fileupload'),
        ),
    ]
